name: daveBot-project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9   
  - pip
  - nd2
  - notebook 
  - postgresql       
  - ipykernel       # lets you use this env as a kernel in Jupyter
  - pip:
      - nd2reader
      - tifffile
      - attrs==25.3.0
      - boxsdk==3.14.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - cryptography==46.0.1
      - idna==3.10
      - PyJWT==2.10.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - six==1.17.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - pycparser==2.23
      - setuptools==58.0.4
      - label-studio
