name: daveBot-project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10   # or whichever version you want standardized
  - pip
  - nd2
  - notebook        # Jupyter Notebook support
  - ipykernel       # lets you use this env as a kernel in Jupyter
  - pip:
      - nd2reader
      - tifffile
